import Head from 'next/head'
//import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useSession } from 'next-auth/react'

//const inter = Inter({ subsets: ['latin'] })

export default function Home() {
	const { data: session, status: sessionStatus } = useSession()
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className={styles.main}>
				<p>dashboard</p>
				<p style={{ width: 300, wordWrap: 'break-word' }}>
					{JSON.stringify(session)}
				</p>
			</main>
		</>
	)
}
