import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import LnurlAuthSignIn from './auth/signin/lnurl'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className={styles.main}>
				<div className={styles.description}>
					Click the QR Code or scan it with a lightning wallet to login
				</div>
				<LnurlAuthSignIn callbackUrl={'/dashboard'} />

				<div>
					<div className={styles.description}>
						Don&apos;t have a wallet? Try one of these:
					</div>

					<ul className={styles.list}>
						<li className={styles.description}>
							<a href='https://breez.technology/'>Breez</a>
						</li>
						<li className={styles.description}>
							<a href='https://phoenix.acinq.co/'>Phoenix</a>
						</li>
						<li className={styles.description}>
							<a href='https://zeusln.app/'>Zeus</a>
						</li>
						<li className={styles.description}>
							<a href='https://lightning-wallet.com/'>Lightning Wallet</a>
						</li>
						<li className={styles.description}>
							<a href='https://lightningjoule.com/'>Joule</a>
						</li>
						<li className={styles.description}>
							<a href='https://bluewallet.io/'>BlueWallet</a>
						</li>
					</ul>
				</div>

				<a
					href='https://github.com/fiatjaf/lnurl-rfc/blob/master/lnurl-auth.md'
					className={styles.description}
					target='_blank'
					rel='noopener noreferrer'>
					<div className={styles.list}>What is Lightning Login?</div>
				</a>
			</main>
		</>
	)
}
