import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import LnurlAuthSignIn from './auth/signin/lnurl'
import { classNames } from '@/utils/utils'
import { getServerSession } from 'next-auth'
import { authOptions } from './api/auth/[...nextauth]'
import axios from 'axios'
import { getEncoded } from './api/auth/lnurl/generate-secret'

const inter = Inter({ subsets: ['latin'] })

export default function Login({ lnurlAuthLoginInfo }: any) {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className={classNames(inter.className, 'p-4')}>
				<div className='text-3xl text-center font-bold mt-4'>LocalSats.org</div>
				<div
					id='body'
					style={{
						width: '100%',
						display: 'flex',
						justifyContent: 'center',
						flexDirection: 'column',
						alignItems: 'center'
					}}>
					<div className='text-center my-8'>
						Click the QR Code or scan it with a lightning wallet to login
					</div>
					<div style={{ marginBottom: 24 }}>
						<LnurlAuthSignIn
							callbackUrl={'/home'}
							lnurlAuthLoginInfo={lnurlAuthLoginInfo}
						/>
					</div>

					<div style={{ marginTop: 48 }}>
						Don&apos;t have a wallet? Try one of these:
					</div>

					<ul style={{ marginBottom: 56 }}>
						<li>
							<a
								className='underline text-blue-500'
								href='https://breez.technology/'>
								Breez
							</a>
						</li>
						<li className={styles.description}>
							<a
								className='underline text-blue-500'
								href='https://phoenix.acinq.co/'>
								Phoenix
							</a>
						</li>
						<li className={styles.description}>
							<a
								className='underline text-blue-500'
								href='https://bluewallet.io/'>
								BlueWallet
							</a>
						</li>
						<li className={styles.description}>
							<a className='underline text-blue-500' href='https://zeusln.app/'>
								Zeus
							</a>
						</li>
					</ul>

					<a
						href='https://github.com/fiatjaf/lnurl-rfc/blob/master/lnurl-auth.md'
						className='underline text-blue-500'
						target='_blank'
						rel='noopener noreferrer'>
						<div className={styles.list}>Learn more about Lightning login</div>
					</a>
				</div>
			</main>
		</>
	)
}

export const getServerSideProps = async function ({ req, res }) {
	const lnurlAuthLoginInfo = await getEncoded()

	return {
		props: { lnurlAuthLoginInfo }
	}
}
